### ISSUE TITLE
Learning code

### ISSUE THREAD

**Issue by kenzwr1025** [aws-samples/aws-elastic-beanstalk-express-js-sample#1]

**Comment by kenzwr1025** [comment]
Trying to learn the aws console and understand code no experience just for personal use

**Comment by anacunha** [comment]
Hi @kenzwr1025!

This sample project is part of the [AWS DevOps Engineer Learning Path](https://aws.amazon.com/getting-started/learning-path-devops-engineer/).

You can find step-by-step instructions on how to use this sample project to create a continuous delivery pipeline at https://aws.amazon.com/getting-started/hands-on/create-continuous-delivery-pipeline-codepipeline-codebuild/

If you're having issues with the project and/or instructions, please let us know.

Thanks,
Ana

**Comment by anacunha** [comment]
Closing this issue. @kenzwr1025 feel free to reach out in case you need any help with this project.
